import { Domain, Event, CouncilMember, Stat } from './types';

export const DOMAINS: Domain[] = [
  {
    id: 'web',
    title: 'Web Development',
    icon: 'Globe',
    description: 'Building the modern web with React, Next.js, and Node.',
    detailedDescription: 'Master the full stack of web technologies. From responsive UI design with Tailwind to scalable backends using Node.js and cloud infrastructure.',
  },
  {
    id: 'app',
    title: 'App Development',
    icon: 'Smartphone',
    description: 'Crafting native experiences for iOS and Android.',
    detailedDescription: 'Dive into Flutter, React Native, and Swift. We build applications that solve real-world problems with intuitive mobile interfaces.',
  },
  {
    id: 'ai',
    title: 'AI / ML',
    icon: 'Brain',
    description: 'Engineering intelligent systems and neural networks.',
    detailedDescription: 'Explore the frontiers of Artificial Intelligence. From Computer Vision to NLP, we build models that learn and adapt.',
  },
  {
    id: 'cp',
    title: 'Competitive Coding',
    icon: 'Code',
    description: 'Mastering algorithms and data structures.',
    detailedDescription: 'Prepare for the toughest coding interviews and contests (ICPC). We focus on efficiency, optimization, and problem-solving strategies.',
  },
  {
    id: 'uiux',
    title: 'UI / UX Design',
    icon: 'PenTool',
    description: 'Designing intuitive and beautiful user journeys.',
    detailedDescription: 'Where art meets functionality. We use Figma and Spline to create prototypes that delight users and drive engagement.',
  },
  {
    id: 'cyber',
    title: 'Cybersecurity',
    icon: 'Shield',
    description: 'Protecting digital assets and ethical hacking.',
    detailedDescription: 'Learn to defend against digital threats. We cover penetration testing, cryptography, and secure coding practices.',
  },
];

export const EVENTS: Event[] = [
  {
    id: '1',
    title: 'Paradox Hackathon 2024',
    date: 'May 2024',
    description: 'A 36-hour nonstop coding marathon fostering innovation and sleepless nights.',
    image: 'https://picsum.photos/800/600?random=1',
    outcome: 'Over 50 projects submitted, 3 winners incubated.',
  },
  {
    id: '2',
    title: 'AI Workshop Series',
    date: 'August 2024',
    description: 'Hands-on bootcamp on Generative AI and LLMs.',
    image: 'https://picsum.photos/800/600?random=2',
    outcome: '200+ attendees built their own chatbots.',
  },
  {
    id: '3',
    title: 'Open Source Summit',
    date: 'October 2024',
    description: 'Guest lectures from industry leaders on contributing to OSS.',
    image: 'https://picsum.photos/800/600?random=3',
    outcome: 'Record number of PRs merged into major repos.',
  },
  {
    id: '4',
    title: 'Cyber CTF League',
    date: 'November 2024',
    description: 'Capture The Flag competition testing security skills.',
    image: 'https://picsum.photos/800/600?random=11',
    outcome: 'Identified top 10 security researchers in campus.',
  },
  {
    id: '5',
    title: 'React Advanced Patterns',
    date: 'December 2024',
    description: 'Deep dive into hooks, context, and performance optimization.',
    image: 'https://picsum.photos/800/600?random=12',
    outcome: 'Participants refactored legacy codebases successfully.',
  },
  {
    id: '6',
    title: 'Flutter Festival',
    date: 'January 2025',
    description: 'Building cross-platform apps in record time.',
    image: 'https://picsum.photos/800/600?random=13',
    outcome: '15 Apps published to Play Store.',
  },
  {
    id: '7',
    title: 'Design Sprint 2025',
    date: 'February 2025',
    description: 'UI/UX challenge to redesign popular apps.',
    image: 'https://picsum.photos/800/600?random=14',
    outcome: 'Innovative designs featured in college magazine.',
  },
  {
    id: '8',
    title: 'Algorithmic Arena',
    date: 'March 2025',
    description: 'Weekly competitive programming contests.',
    image: 'https://picsum.photos/800/600?random=15',
    outcome: 'Selected college team for ICPC regionals.',
  },
  {
    id: '9',
    title: 'Cloud Computing 101',
    date: 'April 2025',
    description: 'Introduction to AWS and Azure services.',
    image: 'https://picsum.photos/800/600?random=16',
    outcome: 'Students certified as Cloud Practitioners.',
  },
  {
    id: '10',
    title: 'Game Dev Weekend',
    date: 'April 2025',
    description: 'Unity and Godot engine workshop.',
    image: 'https://picsum.photos/800/600?random=17',
    outcome: '5 Playable game prototypes created.',
  },
  {
    id: '11',
    title: 'Blockchain Basics',
    date: 'May 2025',
    description: 'Understanding Web3 and Smart Contracts.',
    image: 'https://picsum.photos/800/600?random=18',
    outcome: 'Deployed first smart contract on testnet.',
  },
  {
    id: '12',
    title: 'Tech Talk: Future of AI',
    date: 'June 2025',
    description: 'Panel discussion with professors and industry experts.',
    image: 'https://picsum.photos/800/600?random=19',
    outcome: 'Insightful Q&A session on ethics in AI.',
  },
];

export const COUNCIL: CouncilMember[] = [
  // Core Team (Top 4)
  {
    id: '1',
    name: 'Aravind K.',
    role: 'President',
    photo: 'https://picsum.photos/300/300?random=4',
    bio: 'Passionate full-stack developer and community builder. Leading CodeCrafters to new heights.',
    linkedin: '#',
    github: '#',
  },
  {
    id: '2',
    name: 'Sneha R.',
    role: 'Vice President',
    photo: 'https://picsum.photos/300/300?random=5',
    bio: 'AI enthusiast with a knack for system architecture. Loves solving complex problems.',
    linkedin: '#',
    github: '#',
  },
  {
    id: '3',
    name: 'Rahul V.',
    role: 'Secretary',
    photo: 'https://picsum.photos/300/300?random=6',
    bio: 'Organizer extraordinaire. Ensuring every hackathon and workshop runs smoothly.',
    linkedin: '#',
  },
  {
    id: '4',
    name: 'Priya M.',
    role: 'Tech Lead',
    photo: 'https://picsum.photos/300/300?random=7',
    bio: 'Creative soul obsessed with pixels and user experience. Making things look good.',
    linkedin: '#',
    github: '#',
  },
  // Heads
  { id: '5', name: 'Vikram S.', role: 'Web Head', photo: 'https://picsum.photos/300/300?random=20', bio: 'React Wizard.', linkedin: '#' },
  { id: '6', name: 'Ananya P.', role: 'App Head', photo: 'https://picsum.photos/300/300?random=21', bio: 'Flutter Expert.', linkedin: '#' },
  { id: '7', name: 'Karthik J.', role: 'AI Head', photo: 'https://picsum.photos/300/300?random=22', bio: 'Data Scientist.', linkedin: '#' },
  { id: '8', name: 'Rohan D.', role: 'CP Head', photo: 'https://picsum.photos/300/300?random=23', bio: 'Algorithm Master.', linkedin: '#' },
  { id: '9', name: 'Meera L.', role: 'Design Head', photo: 'https://picsum.photos/300/300?random=24', bio: 'UI/UX Artist.', linkedin: '#' },
  { id: '10', name: 'Sanjay B.', role: 'Cyber Head', photo: 'https://picsum.photos/300/300?random=25', bio: 'Security Analyst.', linkedin: '#' },
  { id: '11', name: 'Divya K.', role: 'Events Head', photo: 'https://picsum.photos/300/300?random=26', bio: 'Logistics Queen.', linkedin: '#' },
  { id: '12', name: 'Arjun M.', role: 'Marketing Head', photo: 'https://picsum.photos/300/300?random=27', bio: 'Social Media Guru.', linkedin: '#' },
  // Coordinators
  { id: '13', name: 'Naveen T.', role: 'Web Co-ord', photo: 'https://picsum.photos/300/300?random=28', bio: 'Frontend Dev.', linkedin: '#' },
  { id: '14', name: 'Pooja S.', role: 'App Co-ord', photo: 'https://picsum.photos/300/300?random=29', bio: 'Android Dev.', linkedin: '#' },
  { id: '15', name: 'Varun R.', role: 'AI Co-ord', photo: 'https://picsum.photos/300/300?random=30', bio: 'ML Engineer.', linkedin: '#' },
  { id: '16', name: 'Swati G.', role: 'CP Co-ord', photo: 'https://picsum.photos/300/300?random=31', bio: 'Competitive Coder.', linkedin: '#' },
  { id: '17', name: 'Deepak H.', role: 'Design Co-ord', photo: 'https://picsum.photos/300/300?random=32', bio: 'Graphic Designer.', linkedin: '#' },
  { id: '18', name: 'Amit K.', role: 'Cyber Co-ord', photo: 'https://picsum.photos/300/300?random=33', bio: 'Ethical Hacker.', linkedin: '#' },
  { id: '19', name: 'Neha J.', role: 'Events Co-ord', photo: 'https://picsum.photos/300/300?random=34', bio: 'Event Planner.', linkedin: '#' },
  { id: '20', name: 'Rajesh P.', role: 'Tech Co-ord', photo: 'https://picsum.photos/300/300?random=35', bio: 'Backend Dev.', linkedin: '#' },
  { id: '21', name: 'Simran K.', role: 'Content Co-ord', photo: 'https://picsum.photos/300/300?random=36', bio: 'Writer.', linkedin: '#' },
];

export const STATS: Stat[] = [
  { label: 'Active Members', value: '500+' },
  { label: 'Projects Shipped', value: '45+' },
  { label: 'Events Hosted', value: '20+' },
  { label: 'Hackathon Wins', value: '12' },
];
